# Домашнее задание № 4

## по дисциплине: Линейная алгебра

## Системы линейных уравнений. Часть 1

### выполнил: Евгений Кириллов

__1.__ Решить систему уравнений методом Гаусса:

### $$\begin{cases}x_{1}+x_{2}-x_{3}-2x_{4}=0, \\2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\x_{1}+x_{2}-3x_{3}+x_{4}=4\end{cases}$$

систему уравнений в виде расширенной матрицы:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 1 & -1 & -2\\ 2 & 1 & -1 & 1\\ 1 & 1 & -3 & 1\end{matrix}\right|\begin{matrix}0\\ -2\\4\end{matrix}\end{pmatrix}$$

вычтем из 2й строки 1ю умноженную на 2 и вычтем из 3й строки 1ю:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 1 & -1 & -2\\ 0 & -1 & 1 & 5\\ 0 & 0 & -2 & 3\end{matrix}\right|\begin{matrix}0\\ -2\\4\end{matrix}\end{pmatrix}$$

т.к. количество переменных превышает ранг матрицы (3), то, следовательно, система уравнений совместна и имеет бесконечное количество решений

пусть $x_{4}=с$, тогда:

### $$\begin{cases}x_{1}=-3с-2, \\x_{2}=6.5с, \\x_{3}=1.5с-2, \\x_{4}=с\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

### а)

### $$\begin{cases}3x_{1}-x_{2}+x_{3}=4, \\2x_{1}-5x_{2}-3x_{3}=-17, \\x_{1}+x_{2}-x_{3}=0;\end{cases}$$

напишем для решения задачи вот такую замечательную функцию:

In [1]:
import numpy as np

In [2]:
def check_compatibility(A_extended):
    
    # из расширенной матрицы создаём обычную
    A = [_[:-1] for _ in A_extended]
    
    # считаем количество неизвестных в системе уравнений
    n = len(A[0])
    
    # переводим матрицы из списков в массивы
    A = np.array(A)
    A_extended = np.array(A_extended)
    
    # считаем ранги
    rank_A = np.linalg.matrix_rank(A)
    rank_A_extended = np.linalg.matrix_rank(A_extended)
    
    print(f'\nматрица A: \n{A}')
    print(f'\nрасширенная матрица A: \n{A_extended}')
    
    print(f'\nранг матрицы A: {rank_A}')
    print(f'ранг расширенной матрицы A: {rank_A_extended}')
    print(f'количество переменных: {n}')
    
    print('\n\nответ:')
    
    # проверяем на совместимость и считаем количество решений
    if rank_A < rank_A_extended:
        print('система несовместна')
    
    elif rank_A == rank_A_extended == n:
        print('система совместна, определена, имеет единственное решение')
        
    elif rank_A == rank_A_extended < n:
        print('система совместна, имеет бесконечное количество решений')
        
    else:
        print('где-то тут ошибка')
    
    return None

In [3]:
x = [3, -1, 1, 4]
y = [2, -5, -3, -17]
z = [1, 1, -1, 0]

check_compatibility([x, y, z])


матрица A: 
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]

расширенная матрица A: 
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

ранг матрицы A: 3
ранг расширенной матрицы A: 3
количество переменных: 3


ответ:
система совместна, определена, имеет единственное решение


### б)

### $$\begin{cases}2x_{1}-4x_{2}+6x_{3}=1, \\x_{1}-2x_{2}+3x_{3}=-2, \\3x_{1}-6x_{2}+9x_{3}=5;\end{cases}$$

In [4]:
x = [2, -4, 6, 1]
y = [1, -2, 3, -2]
z = [3, -6, 9, 5]

check_compatibility([x, y, z])


матрица A: 
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]

расширенная матрица A: 
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

ранг матрицы A: 1
ранг расширенной матрицы A: 2
количество переменных: 3


ответ:
система несовместна


### в)

### $$\begin{cases}x_{1}+2x_{2}+5x_{3}=4, \\3x_{1}+x_{2}-8x_{3}=-2. \end{cases}$$

In [5]:
x = [1, 2, 5, 4]
y = [3, 1, -8, -2]

check_compatibility([x, y])


матрица A: 
[[ 1  2  5]
 [ 3  1 -8]]

расширенная матрица A: 
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

ранг матрицы A: 2
ранг расширенной матрицы A: 2
количество переменных: 3


ответ:
система совместна, имеет бесконечное количество решений


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

### $$\tilde{A}=\begin{pmatrix}\left.\begin{matrix}1 & 3 & -2 & 4\\ 0 & 5 & 0 & 1\\ 0 & 0 & 3 & 0\\ 0 & 0 & 0 & 2\end{matrix}\right|\begin{matrix}3\\ 2\\4\\1\end{matrix}\end{pmatrix}$$

In [6]:
x = [1, 3, -2, 4, 3]
y = [0, 5, 0, 1, 2]
z = [0, 0, 3, 0, 4]
i = [0, 0, 0, 2, 1]

check_compatibility([x, y, z, i])


матрица A: 
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

расширенная матрица A: 
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

ранг матрицы A: 4
ранг расширенной матрицы A: 4
количество переменных: 4


ответ:
система совместна, определена, имеет единственное решение


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

### $$\tilde{A}=\begin{pmatrix}\left.\begin{matrix}1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9\end{matrix}\right|\begin{matrix}a\\ b\\c\end{matrix}\end{pmatrix}$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

вычтем из 2й строки 1ю умноженную на 4:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 2 & 3\\ 0 & -3 & -6\\ 7 & 8 & 9\end{matrix}\right|\begin{matrix}a\\ b-4a\\c\end{matrix}\end{pmatrix}$$

вычтем из 3й строки 1ю умноженную на 7:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 2 & 3\\ 0 & -3 & -6\\ 0 & -6 & -12\end{matrix}\right|\begin{matrix}a\\ b-4a\\c-7a\end{matrix}\end{pmatrix}$$

вычтем из 3й строки 2ю умноженную на 2:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 2 & 3\\ 0 & -3 & -6\\ 0 & 0 & 0\end{matrix}\right|\begin{matrix}a\\ b-4a\\a-2b+c\end{matrix}\end{pmatrix}$$

тогда при $a-2b+c\neq0$ ранг матрицы $A$ будет меньше ранга матрицы $\tilde{A}$ и система будет несовместной

## Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

### а)

### $$\begin{cases}x_{1}-2x_{2}=1 \\3x_{1}-4x_{2}=7\end{cases}$$

найдём определитель матрицы коэффициентов:

In [7]:
A = np.array([[1, -2], [3, -4]])
print(f'{np.linalg.det(A):.0f}')

2


$2\neq 0$, следовательно, система совместна

найдём определители $detA_{1}$, $detA_{2}$:

In [8]:
A1 = np.array([[1, -2], [7, -4]])
print(f'{np.linalg.det(A1):.0f}')

10


In [9]:
A2 = np.array([[1, 1], [3, 7]])
print(f'{np.linalg.det(A2):.0f}')

4


найдём решение по формулам Крамера:

### $$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5$$

### $$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$$

### б)

### $$\begin{cases}2x_{1}-x_{2}+5x_{3}=10 \\x_{1}+x_{2}-3x_{3}=-2 \\2x_{1}+4x_{2}+x_{3}=1\end{cases}$$

найдём определитель матрицы коэффициентов:

In [10]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'{np.linalg.det(A):.0f}')

43


$43\neq 0$, следовательно, система совместна

найдём определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

In [11]:
A1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
print(f'{np.linalg.det(A1):.0f}')

86


In [12]:
A2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
print(f'{np.linalg.det(A2):.0f}')

-43


In [13]:
A3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'{np.linalg.det(A3):.0f}')

43


найдём решение по формулам Крамера:

### $$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2$$

### $$x_{2} = \frac{detA_{2}}{detA} = -\frac{43}{43}=-1$$

### $$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$$

__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

### а)

### $$\begin{pmatrix}1 & 2 & 4 \\ 2 & 9 & 12 \\ 3 & 26 & 30\end{pmatrix}$$

напишем для решения задачи вот такую замечательную функцию:

In [14]:
def form_L_and_U_matrixes(U):
    # функция делает LU разложение некой матрицы
    # функция принимает на вход матрицу
    # функция возвращает матрицы L, U
    
    # порядок/размер матрицы U (L)
    n = len(U)
    # болванка под матрицу L
    L = np.eye(n)
    
    # создание матриц U и L
    for i in range(n):
        for ii in range(i, n):
            try:
                L[ii+1, i] = U[ii+1, i] / U[i, i]
                U[ii+1] = U[ii+1] - U[i] * L[ii+1, i]
            except:
                None
                
    return L, U

In [15]:
A = [[1, 2, 4], [2, 9, 12], [3, 26, 30]]
A = np.array(A, dtype=float)

In [16]:
form_L_and_U_matrixes(A)[0]

array([[1., 0., 0.],
       [2., 1., 0.],
       [3., 4., 1.]])

### б)

### $$\begin{pmatrix}1 & 1 & 2 & 4\\ 2 & 5 & 8 & 9\\ 3 & 18 & 29 & 18\\4 & 22 & 53 & 33\end{pmatrix}$$

In [17]:
A = [[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]]
A = np.array(A, dtype=float)

In [18]:
form_L_and_U_matrixes(A)[0]

array([[1., 0., 0., 0.],
       [2., 1., 0., 0.],
       [3., 5., 1., 0.],
       [4., 6., 7., 1.]])

__3.__ Решить систему линейных уравнений методом $LU$-разложения

### $$\begin{cases}2x_{1}+x_{2}+3x_{3}=1 \\11x_{1}+7x_{2}+5x_{3}=-6 \\9x_{1}+8x_{2}+4x_{3}=-5\end{cases}$$

напишем для решения задачи вот такую замечательную функцию:

In [19]:
def LU_decomposition(A_extended):
    # функция решает систему уравнений путём LU разложения
    # функция принимает на вход систему уравнений в виде расширенной матрицы - A_extended
    # функция возвращает вектор значений x
    
    # вектор значений b
    b = A_extended[:, -1]
    # болванка под матрицу U
    U = A_extended[:, :-1]
    # порядок/размер матрицы U (L)
    n = len(U)
    # болванка под матрицу L
    L = np.eye(n)
    
    # создание матриц U и L
    for i in range(n):
        for ii in range(i, n):
            try:
                L[ii+1, i] = U[ii+1, i] / U[i, i]
                U[ii+1] = U[ii+1] - U[i] * L[ii+1, i]
            except:
                None
                
    def solve_triange_system(triangle_matrix, triangle_matrix_extension):
        # функция решает систему уравнений - матрицу треугольного вида типа L
        # функция принимает на вход саму матрицу - triangle_matrix,
        # а также вектор b из правой стороны уравнения - triangle_matrix_extension
        # функция возвращает вектор значений y из уравнения Ly=b
        
        # также функция решает систему уравнений - матрицу треугольного вида типа U, 
        # если её (матрицу U), а также вектор значений y из уравнения Ly=b, подать на вход развёрнутыми
        # в таком случае функция возвращает вектор значений x из уравнения Ux=y
        # вектор значений x полученный из функции надо развернуть обратно

        result = np.array([0 for _ in range(len(b))], dtype=float)
        for i in range(n):
            line_result = triangle_matrix_extension[i]
            for ii in range(i+1):
                if ii == i:
                    result[i] = line_result / triangle_matrix[i, ii]
                    continue
                line_result -= triangle_matrix[i, ii] * result[ii]

        return result
    
    # расчёт значений y и x, возврат ответа - x
    return solve_triange_system(triangle_matrix=U[::-1, ::-1], 
                     triangle_matrix_extension=solve_triange_system(triangle_matrix=L, triangle_matrix_extension=b)[::-1])[::-1]

In [22]:
# !!!
def LU_decomposition(A_extended):
    # функция решает систему уравнений путём LU разложения
    # функция принимает на вход систему уравнений в виде расширенной матрицы - A_extended
    # функция возвращает вектор значений x
    
    # вектор значений b
    b = A_extended[:, -1]
    # болванка под матрицу U
    U = A_extended[:, :-1]
    # порядок/размер матрицы U (L)
    n = len(U)
    # болванка под матрицу L
    L = np.eye(n)
    
    # создание матриц U и L
    for i in range(n):
        for ii in range(i, n):
            try:
                L[ii+1, i] = U[ii+1, i] / U[i, i]
                U[ii+1] = U[ii+1] - U[i] * L[ii+1, i]
            except:
                None
                
    def solve_triange_system(triangle_matrix, triangle_matrix_extension):
        # функция решает систему уравнений - матрицу треугольного вида типа L
        # функция принимает на вход саму матрицу - triangle_matrix,
        # а также вектор b из правой стороны уравнения - triangle_matrix_extension
        # функция возвращает вектор значений y из уравнения Ly=b
        
        # также функция решает систему уравнений - матрицу треугольного вида типа U, 
        # если её (матрицу U), а также вектор значений y из уравнения Ly=b, подать на вход развёрнутыми
        # в таком случае функция возвращает вектор значений x из уравнения Ux=y
        # вектор значений x полученный из функции надо развернуть обратно

        result = np.array([0 for _ in range(len(triangle_matrix_extension))], dtype=float)
        for i in range(n):
            result[i] = triangle_matrix_extension[i]
            for ii in range(i+1):
                if ii == i:
                    result[i] = result[i] / triangle_matrix[i, ii]
                    continue
                result[i] -= triangle_matrix[i, ii] * result[ii]

        return result
    
    # расчёт значений y и x, возврат ответа - x
    return solve_triange_system(triangle_matrix=U[::-1, ::-1], 
                     triangle_matrix_extension=solve_triange_system(triangle_matrix=L, triangle_matrix_extension=b)[::-1])[::-1]

In [23]:
A_extended = [[2, 1, 3, 1], [11, 7, 5, -6], [9, 8, 4, -5]]
A_extended = np.array(A_extended, dtype=float)
LU_decomposition(A_extended)

array([-1.,  0.,  1.])

__4.__ Решить систему линейных уравнений методом Холецкого

### $$\begin{cases}81x_{1}-45x_{2}+45x_{3}=531 \\-45x_{1}+50x_{2}-15x_{3}=-460 \\45x_{1}-15x_{2}+38x_{3}=193\end{cases}$$

не успел

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

# см. выше