# Домашнее задание № 4

## по дисциплине: Линейная алгебра

## Системы линейных уравнений. Часть 1

### выполнил: Евгений Кириллов

__1.__ Решить систему уравнений методом Гаусса:

### $$\begin{cases}x_{1}+x_{2}-x_{3}-2x_{4}=0, \\2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\x_{1}+x_{2}-3x_{3}+x_{4}=4\end{cases}$$

систему уравнений в виде расширенной матрицы:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 1 & -1 & -2\\ 2 & 1 & -1 & 1\\ 1 & 1 & -3 & 1\end{matrix}\right|\begin{matrix}0\\ -2\\4\end{matrix}\end{pmatrix}$$

вычтем из 2й строки 1ю умноженную на 2 и вычтем из 3й строки 1ю:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 1 & -1 & -2\\ 0 & -1 & 1 & 5\\ 0 & 0 & -2 & 3\end{matrix}\right|\begin{matrix}0\\ -2\\4\end{matrix}\end{pmatrix}$$

т.к. количество переменных превышает ранг матрицы (3), то, следовательно, система уравнений совместна и имеет бесконечное количество решений

пусть $x_{4}=с$, тогда:

### $$\begin{cases}x_{1}=-3с-2, \\x_{2}=6.5с, \\x_{3}=1.5с-2, \\x_{4}=с\end{cases}$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

### а)

### $$\begin{cases}3x_{1}-x_{2}+x_{3}=4, \\2x_{1}-5x_{2}-3x_{3}=-17, \\x_{1}+x_{2}-x_{3}=0;\end{cases}$$

напишем для решения задачи вот такую вот замечательную функцию:

In [73]:
import numpy as np

In [74]:
def check_compatibility(A_extended):
    
    # из расширенной матрицы создаём обычную
    A = [_[:-1] for _ in A_extended]
    
    # считаем количество неизвестных в системе уравнений
    n = len(A[0])
    
    # переводим матрицы из списков в массивы
    A = np.array(A)
    A_extended = np.array(A_extended)
    
    # считаем ранги
    rank_A = np.linalg.matrix_rank(A)
    rank_A_extended = np.linalg.matrix_rank(A_extended)
    
    print(f'\nматрица A: \n{A}')
    print(f'\nрасширенная матрица A: \n{A_extended}')
    
    print(f'\nранг матрицы A: {rank_A}')
    print(f'ранг расширенной матрицы A: {rank_A_extended}')
    print(f'количество переменных: {n}')
    
    print('\n\nответ:')
    
    # проверяем на совместимость и считаем количество решений
    if rank_A < rank_A_extended:
        print('система несовместна')
    
    elif rank_A == rank_A_extended == n:
        print('система совместна, определена, имеет единственное решение')
        
    elif rank_A == rank_A_extended < n:
        print('система совместна, имеет бесконечное количество решений')
        
    else:
        print('где-то тут ошибка')
    
    return None

In [78]:
x = [3, -1, 1, 4]
y = [2, -5, -3, -17]
z = [1, 1, -1, 0]

check_compatibility([x, y, z])


матрица A: 
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]

расширенная матрица A: 
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

ранг матрицы A: 3
ранг расширенной матрицы A: 3
количество переменных: 3


ответ:
система совместна, определена, имеет единственное решение


### б)

### $$\begin{cases}2x_{1}-4x_{2}+6x_{3}=1, \\x_{1}-2x_{2}+3x_{3}=-2, \\3x_{1}-6x_{2}+9x_{3}=5;\end{cases}$$

In [79]:
x = [2, -4, 6, 1]
y = [1, -2, 3, -2]
z = [3, -6, 9, 5]

check_compatibility([x, y, z])


матрица A: 
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]

расширенная матрица A: 
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

ранг матрицы A: 1
ранг расширенной матрицы A: 2
количество переменных: 3


ответ:
система несовместна


### в)

### $$\begin{cases}x_{1}+2x_{2}+5x_{3}=4, \\3x_{1}+x_{2}-8x_{3}=-2. \end{cases}$$

In [80]:
x = [1, 2, 5, 4]
y = [3, 1, -8, -2]

check_compatibility([x, y])


матрица A: 
[[ 1  2  5]
 [ 3  1 -8]]

расширенная матрица A: 
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

ранг матрицы A: 2
ранг расширенной матрицы A: 2
количество переменных: 3


ответ:
система совместна, имеет бесконечное количество решений


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

### $$\tilde{A}=\begin{pmatrix}\left.\begin{matrix}1 & 3 & -2 & 4\\ 0 & 5 & 0 & 1\\ 0 & 0 & 3 & 0\\ 0 & 0 & 0 & 2\end{matrix}\right|\begin{matrix}3\\ 2\\4\\1\end{matrix}\end{pmatrix}$$

In [81]:
x = [1, 3, -2, 4, 3]
y = [0, 5, 0, 1, 2]
z = [0, 0, 3, 0, 4]
i = [0, 0, 0, 2, 1]

check_compatibility([x, y, z, i])


матрица A: 
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

расширенная матрица A: 
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

ранг матрицы A: 4
ранг расширенной матрицы A: 4
количество переменных: 4


ответ:
система совместна, определена, имеет единственное решение


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

### $$\tilde{A}=\begin{pmatrix}\left.\begin{matrix}1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9\end{matrix}\right|\begin{matrix}a\\ b\\c\end{matrix}\end{pmatrix}$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

вычтем из 2й строки 1ю умноженную на 4:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 2 & 3\\ 0 & -3 & -6\\ 7 & 8 & 9\end{matrix}\right|\begin{matrix}a\\ b-4a\\c\end{matrix}\end{pmatrix}$$

вычтем из 3й строки 1ю умноженную на 7:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 2 & 3\\ 0 & -3 & -6\\ 0 & -6 & -12\end{matrix}\right|\begin{matrix}a\\ b-4a\\c-7a\end{matrix}\end{pmatrix}$$

вычтем из 3й строки 2ю умноженную на 2:

### $$\begin{pmatrix}\left.\begin{matrix}1 & 2 & 3\\ 0 & -3 & -6\\ 0 & 0 & 0\end{matrix}\right|\begin{matrix}a\\ b-4a\\a-2b+c\end{matrix}\end{pmatrix}$$

тогда при $a-2b+c\neq0$ ранг матрицы $A$ будет меньше ранга матрицы $\tilde{A}$ и система будет несовместной

## Системы линейных уравнений. Часть 2