# Домашнее задание № 2

## по дисциплине: Линейная алгебра

## Матрицы и матричные операции

### выполнил: Евгений Кириллов

# Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

#### а)

матрицу A нельзя умножить на матрицу B (и наоборот) т.к. число столбцов одной матрицы не равно числу строк другой

#### б)

$A \cdot B$ имеет размерность $2 \times 3$

$B \cdot A$ перемножить нельзя

#### в)

$A \cdot B$ имеет размерность $8 \times 8$

$B \cdot A$ имеет размерность $3 \times 3$

#### г)

$A \cdot B$ имеет размерность $4 \times 4$

$B \cdot A$ имеет размерность $4 \times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

### $$A+B=B+A=\begin{pmatrix}1 & -2\\ 3 & 0\end{pmatrix} + \begin{pmatrix}4 & -1\\ 0 & 5\end{pmatrix} = \begin{pmatrix}1+4 & -2+(-1)\\ 3+0 & 0+5\end{pmatrix} = \begin{pmatrix}5 & -3\\ 3 & 5\end{pmatrix}$$

### $$A \cdot B=\begin{pmatrix}1 & -2\\ 3 & 0\end{pmatrix} \cdot \begin{pmatrix}4 & -1\\ 0 & 5\end{pmatrix} = \begin{pmatrix}1\times4 + (-2)\times0& 1\times(-1)+(-2)\times5\\ 3\times4 + 0\times0 & 3\times(-1)+0\times5\end{pmatrix} = \begin{pmatrix}4 & -11\\ 12 & -3\end{pmatrix}$$

### $$B \cdot A=\begin{pmatrix}4 & -1\\ 0 & 5\end{pmatrix} \cdot \begin{pmatrix}1 & -2\\ 3 & 0\end{pmatrix} = \begin{pmatrix}4\times1 + (-1)\times3& 4\times(-2) + (-1)\times0\\ 0\times1 + 5\times3 & 0\times(-2)+5\times0\end{pmatrix} = \begin{pmatrix}1 & -8\\ 15 & 0\end{pmatrix}$$

#### проверим с помощью numpy:

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [3]:
A

array([[ 1, -2],
       [ 3,  0]])

In [4]:
B

array([[ 4, -1],
       [ 0,  5]])

In [5]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [6]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

In [7]:
np.dot(B, A)

array([[ 1, -8],
       [15,  0]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

### $$3A−2B+4C=3\cdot\begin{pmatrix}1 & 7\\ 3 & -6\end{pmatrix} + (-2)\cdot\begin{pmatrix}0 & 5\\ 2 & -1\end{pmatrix}  + 4\cdot\begin{pmatrix}2 & -4\\ 1 & 1\end{pmatrix}= $$

### $$=\begin{pmatrix}3 & 21\\ 9 & -18\end{pmatrix} + \begin{pmatrix}0 & -10\\ -4 & 2\end{pmatrix}  + \begin{pmatrix}8 & -16\\ 4 & 4\end{pmatrix}= \begin{pmatrix}11 & -5\\ 9 & -12\end{pmatrix}$$

#### проверим с помощью numpy:

In [8]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [9]:
A

array([[ 1,  7],
       [ 3, -6]])

In [10]:
B

array([[ 0,  5],
       [ 2, -1]])

In [11]:
C

array([[ 2, -4],
       [ 1,  1]])

In [12]:
3 * A + (-2) * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

### $$A^{T} = \begin{pmatrix}4 & 5 & 2\\ 1 & -2 & 3\end{pmatrix}$$

### $$AA^{T} = \begin{pmatrix}4 & 1\\ 5 & -2\\ 2 & 3\end{pmatrix} \cdot \begin{pmatrix}4 & 5 & 2\\ 1 & -2 & 3\end{pmatrix}=$$

### $$= \begin{pmatrix}4\times4+1\times1 & 4\times5+1\times(-2) & 4\times2+1\times3\\ 5\times4+(-2)\times1 & 5\times5+(-2)\times(-2) & 5\times2+(-2)\times3\\2\times4+3\times1 & 2\times5+3\times(-2) & 2\times2+3\times3\end{pmatrix} =$$

### $$= \begin{pmatrix}17 & 18 & 11\\ 18 & 29 & 4\\11 & 4 & 13\end{pmatrix}$$

### $$A^{T}A = \begin{pmatrix}4 & 5 & 2\\ 1 & -2 & 3\end{pmatrix} \cdot \begin{pmatrix}4 & 1\\ 5 & -2\\ 2 & 3\end{pmatrix}=$$

### $$=\begin{pmatrix}4\times4+5\times5+2\times2 & 4\times1+5\times(-2)+2\times3\\ 1\times4+(-2)\times5+3\times2 & 1\times1+(-2)\times(-2)+3\times3\end{pmatrix}=\begin{pmatrix}45 & 0\\ 0 & 14\end{pmatrix}$$

#### проверим с помощью numpy:

In [13]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [14]:
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [15]:
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [16]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [17]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [18]:
def matrixes_product(A, B):
    
    # проверяем на возможность произведения
    if len(A) != len(B[0]):
        print('матрицы нельзя перемножить')
        return None
    
    # транспонируем матрицу B - так удобнее потом перемножать элементы двух матриц
    B_trans = []
    for i in range(len(B[0])):
        new_line = []
        for ii in range(len(B)):
            new_line.append(B[ii][i])
        B_trans.append(new_line)
    
    # создаём болванку под итоговую матрицу
    m_product = [[0] * len(A) for _ in range(len(A))]
    
    # заполняем болванку
    for i in range(len(m_product)):
        for ii in range(len(m_product[i])):
            m_product[i][ii] = [element for element in zip([m for m in A[i]], [n for n in B_trans[ii]])]
            print(m_product[i][ii])  # демонстрация механизма рассчёта каждого элемента итоговой матрицы
            m_product[i][ii] = sum([element[0] * element[1] for element in m_product[i][ii]])
            print(m_product[i][ii])  # демонстрация механизма рассчёта каждого элемента итоговой матрицы
        
    return m_product

#### проверка работы функции

возьмём матрицы A и B из второго задания

In [19]:
A = [[1, -2], [3, 0]]
B = [[4, -1], [0, 5]]

In [20]:
matrixes_product(A, B)

[(1, 4), (-2, 0)]
4
[(1, -1), (-2, 5)]
-11
[(3, 4), (0, 0)]
12
[(3, -1), (0, 5)]
-3


[[4, -11], [12, -3]]

In [21]:
matrixes_product(B, A)

[(4, 1), (-1, 3)]
1
[(4, -2), (-1, 0)]
-8
[(0, 1), (5, 3)]
15
[(0, -2), (5, 0)]
0


[[1, -8], [15, 0]]

возьмём матрицы A и AT из четвёртого задания

In [22]:
A = [[4, 1], [5, -2], [2, 3]]
AT = [[4, 5, 2], [1, -2, 3]]

In [23]:
matrixes_product(A, AT)

[(4, 4), (1, 1)]
17
[(4, 5), (1, -2)]
18
[(4, 2), (1, 3)]
11
[(5, 4), (-2, 1)]
18
[(5, 5), (-2, -2)]
29
[(5, 2), (-2, 3)]
4
[(2, 4), (3, 1)]
11
[(2, 5), (3, -2)]
4
[(2, 2), (3, 3)]
13


[[17, 18, 11], [18, 29, 4], [11, 4, 13]]

In [24]:
matrixes_product(AT, A)

[(4, 4), (5, 5), (2, 2)]
45
[(4, 1), (5, -2), (2, 3)]
0
[(1, 4), (-2, 5), (3, 2)]
0
[(1, 1), (-2, -2), (3, 3)]
14


[[45, 0], [0, 14]]

#### всё работает!

# Часть 2

__1.__ Вычислить определитель:

#### a)

### $$\begin{vmatrix}sinx & -cosx\\ cosx & sinx\end{vmatrix} = sin(x) \cdot sin(x) - (-cos(x)) \cdot cos(x) = sin^{2}(x) + cos^{2}(x) = 1$$

#### б)

т.к. матрица треугольная, то определитель равен произведению элементов основной диагонали

### $$\begin{vmatrix}4 & 2 & 3\\ 0 & 5 & 1\\ 0 & 0 & 9\end{vmatrix}= 4 \cdot 5 \cdot 9= 180$$

#### в)

### $$\begin{vmatrix}1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9\end{vmatrix}=1\cdot\begin{vmatrix}5 & 6\\ 8 & 9\end{vmatrix}-2\cdot\begin{vmatrix}4 &6\\ 7 & 9\end{vmatrix}+3\cdot\begin{vmatrix}4 & 5\\ 7 & 8\end{vmatrix}=$$

### $$=1\cdot(45-48)-2\cdot(36-42)+3\cdot(32-35)=-3+12-9=0$$

__2.__ Определитель матрицы $A$ равен $4$. Найти:

а) $det(A^{2})$;

т.к. для двух квадратных матриц одинакового размера

### $$det(AB)=detA\cdot detB$$

тогда:

### $$det(A^{2})=det(AA)=detA\cdot detA=4\cdot4=16$$

б) $det(A^{T})$

т.к. определитель транспонированной матрицы равен определителю исходной:

### $$detA^{T}=detA=4$$

в) $det(2A)$

### $$det(2A)=2det(A)=8$$

__3.__  Доказать, что матрица

$$\begin{pmatrix}-2 & 7 & -3\\ 4 & -14 & 6\\ -3 & 7 & 13\end{pmatrix}$$
   
вырожденная.

т.к. матрица называется сингулярной, или вырожденной, если ее определитель равен нулю, тогда найдём определительнашей матрицы

In [29]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

In [30]:
np.linalg.det(A)

0.0

или

если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю, а соответственно матрица является вырожденной

первая и вторая строки данной матрицы линейно засимы: вторая это первая умноженная на -2

__4.__ Найти ранг матрицы:

а) $\begin{pmatrix}1 & 2 & 3\\ 1 & 1 & 1\\ 2 & 3 & 4\end{pmatrix}$

3я строка является сложением 1й и 2й строк, поэтому её можно выбросить

ранг матрицы = 2

проверим:

In [31]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(A)

2

б) $\begin{pmatrix}0 & 0 & 2 & 1\\ 0 & 0 & 2 & 2\\ 0 & 0 & 4 & 3\\ 2 & 3 & 5 & 6\end{pmatrix}$

3я строка является сложением 1й и 2й строк, поэтому её можно выбросить

ранг матрицы = 3

проверим:

In [32]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(A)

3