# Домашнее задание № 5

## по дисциплине: Линейная алгебра

## Сингулярное разложение матриц

### выполнил: Евгений Кириллов

__1.__ Найти с помощью NumPy SVD для матрицы

### $$\begin{pmatrix}1 & 2 & 0\\ 0 & 0 & 5\\ 3 & -4 & 2\\ 1 & 6 & 5\\ 0 & 1 & 0\end{pmatrix}$$

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5], 
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:
U, s, W = np.linalg.svd(A)

In [4]:
U

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [5]:
s

array([8.82, 6.14, 2.53])

In [6]:
W

array([[ 0.07,  0.72,  0.69],
       [-0.37,  0.67, -0.65],
       [-0.93, -0.21,  0.31]])

__2.__ Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

### а)

In [7]:
np.linalg.norm(A, 2)

8.824868854820444

### б)

In [8]:
np.linalg.norm(A, 'fro')

11.045361017187261